In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('bank_note_data.txt',delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42) # 42 is the seed for random function

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
scaler_object = MinMaxScaler()

In [13]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [14]:
scaled_X_train = scaler_object.transform(X_train)

In [15]:
scaled_X_test = scaler_object.transform(X_test)

In [16]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [17]:
model = Sequential()

model.add(Dense(4,input_dim=4,activation='relu')) # input layer

model.add(Dense(8,activation='relu')) # hidden layer

model.add(Dense(1,activation='sigmoid')) # output layer

In [18]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [19]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 0s - loss: 0.7259 - acc: 0.4483
Epoch 2/50
 - 0s - loss: 0.6955 - acc: 0.4690
Epoch 3/50
 - 0s - loss: 0.6804 - acc: 0.5495
Epoch 4/50
 - 0s - loss: 0.6722 - acc: 0.5495
Epoch 5/50
 - 0s - loss: 0.6664 - acc: 0.5495
Epoch 6/50
 - 0s - loss: 0.6610 - acc: 0.5495
Epoch 7/50
 - 0s - loss: 0.6547 - acc: 0.5615
Epoch 8/50
 - 0s - loss: 0.6455 - acc: 0.5898
Epoch 9/50
 - 0s - loss: 0.6333 - acc: 0.6289
Epoch 10/50
 - 0s - loss: 0.6226 - acc: 0.6311
Epoch 11/50
 - 0s - loss: 0.6100 - acc: 0.6409
Epoch 12/50
 - 0s - loss: 0.5977 - acc: 0.6616
Epoch 13/50
 - 0s - loss: 0.5850 - acc: 0.6670
Epoch 14/50
 - 0s - loss: 0.5713 - acc: 0.6681
Epoch 15/50
 - 0s - loss: 0.5576 - acc: 0.6975
Epoch 16/50
 - 0s - loss: 0.5436 - acc: 0.7062
Epoch 17/50
 - 0s - loss: 0.5298 - acc: 0.7236
Epoch 18/50
 - 0s - loss: 0.5157 - acc: 0.7541
Epoch 19/50
 - 0s - loss: 0.5010 - acc: 0.7584
Epoch 20/50
 - 0s - loss: 0.4853 - acc: 0.7911
Epoch 21/50
 - 0s - loss: 0.4675 - acc: 0.8063
Epoch 22/50
 - 0s - lo

In [22]:
# model.predict_classes(scaled_X_test)

In [23]:
model.metrics_names

['loss', 'acc']

In [25]:
from sklearn.metrics import confusion_matrix,classification_report

In [26]:
predictions = model.predict_classes(scaled_X_test)

In [27]:
confusion_matrix(y_test,predictions)

array([[256,   1],
       [  9, 187]])

In [28]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.97      1.00      0.98       257
        1.0       0.99      0.95      0.97       196

avg / total       0.98      0.98      0.98       453



In [29]:
model.save('mysupermodel.h5')

In [30]:
from keras.models import load_model

In [31]:
newmodel = load_model('mysupermodel.h5')

In [32]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    